/**
 * BpfService
 *
 * Read service for Business Process Flows (workflow.category=4).
 *
 * BPFs are stored as `workflow` rows whose canonical definition is in `clientdata`
 * (a stringified JSON document). Companion `processstage` rows are a denormalised
 * view regenerated by the platform on activation — never the source of truth.
 *
 * The clientdata schema is not officially documented; the parser uses the
 * `__class` discriminator to navigate the WorkflowStep tree.
 */

import { PowerPlatformClient } from '../powerplatform-client.js';

export interface BpfStepSummary {
  id: string;
  label?: string;
  attribute?: string;
  required?: boolean;
}

export interface BpfBranchSummary {
  conditionId: string;
  expression?: string;
  targetStageId?: string;
}

export interface BpfStageSummary {
  id: string;
  name?: string;
  entityName?: string;
  steps: BpfStepSummary[];
  branches: BpfBranchSummary[];
}

export interface BpfSummary {
  primaryEntity?: string;
  stages: BpfStageSummary[];
  hasBranches: boolean;
  rawClientData?: unknown;
}

export interface BpfDefinition {
  workflowid: string;
  name: string;
  uniqueName: string | null;
  description: string | null;
  state: 'Draft' | 'Activated' | 'Suspended';
  statecode: number;
  statuscode: number;
  category: number;
  primaryEntity: string | null;
  isManaged: boolean;
  isCustomizable: boolean | null;
  createdOn: string | null;
  modifiedOn: string | null;
  summary?: BpfSummary;
  clientData?: string | null;
  xaml?: string | null;
}

export class BpfService {
  constructor(private client: PowerPlatformClient) {}

  /**
   * Get a BPF by id, with parsed clientdata summary.
   *
   * @param workflowId BPF workflow GUID
   * @param includeRaw If true, also return raw `clientdata` and `xaml` strings
   */
  async getBpf(workflowId: string, includeRaw: boolean = false): Promise<BpfDefinition> {
    const wf = await this.client.get<Record<string, unknown>>(
      `api/data/v9.2/workflows(${workflowId})?$select=workflowid,name,uniquename,description,statecode,statuscode,category,primaryentity,ismanaged,iscustomizable,clientdata,xaml,createdon,modifiedon`
    );

    if (wf.category !== 4) {
      throw new Error(
        `Workflow ${workflowId} is not a Business Process Flow (category=${wf.category})`
      );
    }

    const clientDataStr = (wf.clientdata as string | null) ?? null;
    const summary = this.parseClientData(clientDataStr);

    const customizable = wf.iscustomizable as { Value?: boolean } | boolean | null;
    const isCustomizable =
      typeof customizable === 'boolean'
        ? customizable
        : customizable && typeof customizable === 'object' && 'Value' in customizable
          ? (customizable.Value ?? null)
          : null;

    const result: BpfDefinition = {
      workflowid: wf.workflowid as string,
      name: wf.name as string,
      uniqueName: (wf.uniquename as string) ?? null,
      description: (wf.description as string) ?? null,
      state:
        wf.statecode === 0 ? 'Draft' : wf.statecode === 1 ? 'Activated' : 'Suspended',
      statecode: wf.statecode as number,
      statuscode: wf.statuscode as number,
      category: wf.category as number,
      primaryEntity: (wf.primaryentity as string) ?? null,
      isManaged: Boolean(wf.ismanaged),
      isCustomizable,
      createdOn: (wf.createdon as string) ?? null,
      modifiedOn: (wf.modifiedon as string) ?? null,
      summary,
    };

    if (includeRaw) {
      result.clientData = clientDataStr;
      result.xaml = (wf.xaml as string) ?? null;
    }

    return result;
  }

  /**
   * Parse the BPF clientdata JSON into a structured summary.
   *
   * Schema (observed, undocumented by Microsoft):
   *   WorkflowStep (root)
   *   └─ steps.list[]
   *      ├─ RelationshipCollectionStep            — entity relationships
   *      └─ EntityStep (description = entity)     — one per stage chain segment
   *         └─ steps.list[]
   *            └─ StageStep (description = name)  — a stage
   *               └─ steps.list[]
   *                  ├─ StepStep                  — a field row (label in stepLabels)
   *                  │  └─ ControlStep            — the bound attribute
   *                  ├─ ConditionStep             — branching block
   *                  │  └─ ConditionBranchStep[]  — each branch (description = expression)
   *                  │     └─ SetNextStageStep    — branch target
   *                  └─ CustomJavascriptStep      — custom client script hook
   *
   * Note: a single BPF can produce many EntityStep blocks targeting the same
   * entity because conditional branches fork the chain.
   */
  parseClientData(clientDataStr: string | null): BpfSummary | undefined {
    if (!clientDataStr) return undefined;

    let data: unknown;
    try {
      data = JSON.parse(clientDataStr);
    } catch {
      return { stages: [], hasBranches: false };
    }

    const stages: BpfStageSummary[] = [];
    let primaryEntity: string | undefined;
    let hasBranches = false;

    const root = data as Record<string, unknown>;
    for (const child of this.listOf(root.steps)) {
      if (this.classOf(child) !== 'EntityStep') continue;
      const entityName = (child.description as string) ?? undefined;
      if (!primaryEntity) primaryEntity = entityName;

      for (const stageNode of this.listOf(child.steps)) {
        if (this.classOf(stageNode) !== 'StageStep') continue;
        const stage = this.parseStage(stageNode, entityName);
        if (stage.branches.length > 0) hasBranches = true;
        stages.push(stage);
      }
    }

    return { primaryEntity, stages, hasBranches, rawClientData: data };
  }

  private parseStage(node: Record<string, unknown>, entityName?: string): BpfStageSummary {
    const id = (node.id as string) ?? '';
    const label = this.firstLabel(node);
    const stageName = label ?? (node.description as string | undefined);

    const steps: BpfStepSummary[] = [];
    const branches: BpfBranchSummary[] = [];

    for (const child of this.listOf(node.steps)) {
      const cls = this.classOf(child);
      if (cls === 'StepStep') {
        steps.push(this.parseStepStep(child));
      } else if (cls === 'ConditionStep') {
        for (const b of this.listOf(child.steps)) {
          if (this.classOf(b) !== 'ConditionBranchStep') continue;
          const target = this.listOf(b.steps).find((s) => this.classOf(s) === 'SetNextStageStep');
          branches.push({
            conditionId: (b.id as string) ?? '',
            expression: (b.description as string) ?? undefined,
            targetStageId: target
              ? ((target.targetStageStepId as string) ?? (target.targetId as string) ?? undefined)
              : undefined,
          });
        }
      }
    }

    return { id, name: stageName, entityName, steps, branches };
  }

  private parseStepStep(node: Record<string, unknown>): BpfStepSummary {
    const control = this.listOf(node.steps).find((s) => this.classOf(s) === 'ControlStep');
    const required =
      this.parseBool(node.required) ??
      (control ? this.parseBool(control.required ?? control.requiredLevel) : undefined);

    return {
      id: (node.id as string) ?? '',
      label: this.firstLabel(node) ?? (node.description as string | undefined),
      attribute: control
        ? ((control.controlId as string) ?? (control.dataFieldName as string) ?? undefined)
        : undefined,
      required,
    };
  }

  private classOf(node: unknown): string | undefined {
    if (!node || typeof node !== 'object') return undefined;
    const cls = (node as Record<string, unknown>).__class;
    if (typeof cls !== 'string') return undefined;
    return cls.split(':')[0];
  }

  private listOf(container: unknown): Record<string, unknown>[] {
    if (Array.isArray(container)) {
      return container.filter((x) => x && typeof x === 'object') as Record<string, unknown>[];
    }
    if (container && typeof container === 'object' && 'list' in container) {
      const list = (container as Record<string, unknown>).list;
      if (Array.isArray(list)) {
        return list.filter((x) => x && typeof x === 'object') as Record<string, unknown>[];
      }
    }
    return [];
  }

  private firstLabel(node: Record<string, unknown>): string | undefined {
    const labels = node.stepLabels;
    if (labels && typeof labels === 'object' && 'list' in labels) {
      const list = (labels as Record<string, unknown>).list;
      if (Array.isArray(list) && list.length > 0) {
        const first = list[0] as Record<string, unknown>;
        if (typeof first.description === 'string') return first.description;
      }
    }
    return undefined;
  }

  private parseBool(v: unknown): boolean | undefined {
    if (typeof v === 'boolean') return v;
    if (typeof v === 'string') {
      const lower = v.toLowerCase();
      if (lower === 'true' || lower === 'required') return true;
      if (lower === 'false' || lower === 'none') return false;
    }
    return undefined;
  }
}
